### ISSUE TITLE
Make a good Readme for this

### ISSUE THREAD

**Issue by amanjagdev** [amanjagdev/esri-hacakthon#1]
The readme should include:
- About The Project
- What it does for you?
- Built With
- Getting Started
- Contributing
- Contact

**Comment by Mirza-Hassan** [comment]
@amanjagdev please assign me

**Comment by Mirza-Hassan** [comment]
@amanjagdev please assign me

**Comment by amanjagdev** [comment]
Sure, I have assigned you for it

**Comment by Mirza-Hassan** [comment]
@amanjagdev can you please review this PR https://github.com/amanjagdev/geofence/pull/2

**Comment by Mirza-Hassan** [comment]
@amanjagdev can you please close this PR https://github.com/amanjagdev/geofence/pull/2 and add the label `hacktoberfest-accepted`

**Comment by amanjagdev** [comment]
Closed with #2
